featureblock:
    name: Feature Block with Image
    description: Feature Block with image left or right
    icon: icon-image
    fields:
        section_featureblock_section:
            label: Feature Block with Image
            type: section
            containerAttributes:
                data-icon: icon-image

        section_featureblock_container:
            label: Container Type
            type: balloon-selector
            options:
                container: Container
                container-fluid: Fluid Container
            span: left
            default: container
        section_featureblock_title:
            label: Feature Headline
            type: text
            span: left
        section_featureblock_title_size:
            label: Size
            type: dropdown
            options:
                1: H1
                2: H2
                3: H3
                4: H4
                5: H5
                6: H6
            span: right
        section_featureblock_desc:
            label: Feature Description
            type: richeditor
            toolbarButtons: fullscreen|color|||bold|italic|underline|strikeThrough|subscript|superscript|||formatOL|formatUL|-|undo|redo|||clearFormatting|selectAll|||align|outdent|indent|insertLink|||html
            size: medium
            span: full

        section_styling_head:
            label: Styling
            type: section
            span: full
            containerAttributes: ['ilume-toggle','ilume-hidden']
        section_featureblock_zoom:
            label: Zoom In
            type: balloon-selector
            options:
                zoom: Zoom In
                no-zoom: no Zoom
            span: left
            default: no-zoom
        section_featureblock_image_position:
            label: Image Position
            type: balloon-selector
            span: right
            options:
                left: Left
                right: Right
            default: left
        section_featureblock_textcolor:
            label: Text Color
            type: colorpicker
            availableColors: ["#ffffff","#000000", "#5cb57e"]
            default: "#000000"
            span: left

        section_image_head:
            label: Image
            type: section
            span: full
            containerAttributes: ['ilume-toggle','ilume-hidden']
        section_featureblock_image:
            label: Image
            type: mediafinder
            mode: image
            span: left

        section_block_bg:
            label: Block Background
            type: section
            span: full
            containerAttributes: ['ilume-toggle','ilume-hidden']
        block_bg_color_type:
            label: Background Color
            type: balloon-selector
            options:
                single: Single Color
                double: Two Colors
            span: left
            default: single
        block_bg_color_width:
            label: Background Color Fill
            type: balloon-selector
            options:
                block-only: Block Only
                container-fluid: Fill Parent
            span: right
            default: container-fluid
        bg_color_single:
            label: BG Color
            type: colorpicker
            span: left
            availableColors: ["default-theme", "#000", "#fafafa"]
            default: "default-theme"
            trigger:
                action: show
                field: block_bg_color_type
                condition: value[single]
        bg_color_double_a:
            label: BG Color Top
            type: colorpicker
            span: left
            availableColors: ["default-theme", "#000", "#fafafa"]
            default: "default-theme"
            trigger:
                action: show
                field: block_bg_color_type
                condition: value[double]
        bg_color_double_b:
            label: BG Color Bot
            type: colorpicker
            span: right
            availableColors: ["default-theme", "#000", "#fafafa"]
            default: "default-theme"
            trigger:
                action: show
                field: block_bg_color_type
                condition: value[double]
        block_bg_color_double_split:
            label: Color Switch Pos (% from Top)
            type: number
            span: left
            default: 50
            trigger:
                action: show
                field: block_bg_color_type
                condition: value[double]

        section_block_spacing:
            label: Block Spacing
            type: section
            span: full
            containerAttributes: ['ilume-toggle','ilume-hidden']
        block_spacing_top:
            label: Spacing Top (<value> em)
            type: number
            min: 0
            span: left
            default: 0
            comment: A value of 1 em equals 16px on Desktop Screen Size
        block_spacing_bot:
            label: Spacing Bot (<value> em)
            type: number
            min: 0
            span: right
            default: 0
            comment: A value of 1 em equals 16px on Desktop Screen Size